Run checks on PRs (#150)
* workflows: configure CI workflow for cl3 branch

* PartitionChangeBuilderTest: fix metadata version

* Enable retries

Some tests are flaky

* MINOR: Use SHA256withRSA instead of SHA1withRSA when running SslTransportLayerTest (#20961)

`SHA1withRSA` is disabled in some linux distribution, such as Fedora 43
server, which results in the following error. Hence, this PR adopts the
solution suggested by @gaurav-narula in
https://github.com/apache/kafka/pull/20561#issuecomment-3378701638,
which is to use `SHA256withRSA` instead of `SHA1withRSA`

```
Gradle Test Run :clients:test > Gradle Test Executor 28 > Tls13SslFactoryTest > testSslFactoryConfiguration() FAILED
    org.apache.kafka.common.config.ConfigException: Invalid value javax.net.ssl.SSLHandshakeException: (handshake_failure) No available authentication scheme for configuration A client SSLEngine created with the provided settings can't connect to a server SSLEngine created with those settings.
        at app//org.apache.kafka.common.security.ssl.SslFactory.configure(SslFactory.java:105)
        at app//org.apache.kafka.common.security.ssl.SslFactoryTest.testSslFactoryConfiguration(SslFactoryTest.java:80)
        at java.base@21.0.9/java.lang.reflect.Method.invoke(Method.java:580)
        at java.base@21.0.9/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base@21.0.9/java.util.ArrayList.forEach(ArrayList.java:1596)
```

Reviewers: Chia-Ping Tsai <chia7712@gmail.com>

* MINOR: Skip testDsaKeyPair when DSA algorithm is not supported (#20967)

Background:
https://github.com/apache/kafka/pull/20961#issuecomment-3566975687

```
Gradle Test Run :clients:test > Gradle Test Executor 7 >
SslTransportLayerTest > testDsaKeyPair(Args) >
"testDsaKeyPair(Args).args=tlsProtocol=TLSv1.2, useInlinePem=true"
FAILED     org.opentest4j.AssertionFailedError: Channel 0 was not ready
after 30 seconds ==> expected: <true> but was: <false>         at
app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
at
app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
at app//org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
at app//org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
at app//org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:214)
at
app//org.apache.kafka.common.network.NetworkTestUtils.waitForChannelReady(NetworkTestUtils.java:107)
at
app//org.apache.kafka.common.network.NetworkTestUtils.checkClientConnection(NetworkTestUtils.java:70)
at
app//org.apache.kafka.common.network.SslTransportLayerTest.verifySslConfigs(SslTransportLayerTest.java:1326)
at
app//org.apache.kafka.common.network.SslTransportLayerTest.testDsaKeyPair(SslTransportLayerTest.java:483)

```

Reviewers: Gaurav Narula <gaurav_narula2@apple.com>, Chia-Ping Tsai
 <chia7712@gmail.com>

* ci: invoke RAT

---------

Co-authored-by: Ming-Yen Chung <mingyen066@gmail.com>
Co-authored-by: Jian <fujian1115@gmail.com>