Add dynamic mirror reconfiguration
This patch adds dynamic mirror reconfiguration using AlterConfig API.
All mirror configurations can now be updated dynamically, and this would
cause a reconnection of both MMM and fetchers. This happens at the next
metadata refresh.

Example:

```sh
$ bin/kafka-configs.sh --bootstrap-server :"${server4[cli]}" --entity-type mirrors --entity-name my-mirror --alter \
    --add-config invalid.config=foo
Error while executing config command with args '--bootstrap-server :9094 --entity-type mirrors --entity-name my-mirror --alter --add-config invalid.config=foo'
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.InvalidConfigurationException: Unknown mirror configuration: invalid.config
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:173)
	at kafka.admin.ConfigCommand$.alterResourceConfig(ConfigCommand.scala:432)
	at kafka.admin.ConfigCommand$.alterConfig(ConfigCommand.scala:194)
	at kafka.admin.ConfigCommand$.processCommand(ConfigCommand.scala:166)
	at kafka.admin.ConfigCommand$.main(ConfigCommand.scala:88)
	at kafka.admin.ConfigCommand.main(ConfigCommand.scala)
Caused by: org.apache.kafka.common.errors.InvalidConfigurationException: Unknown mirror configuration: invalid.config

$ bin/kafka-configs.sh --bootstrap-server :"${server4[cli]}" --entity-type mirrors --entity-name my-mirror --alter \
    --add-config bootstrap.servers=localhost:"${server2[cli]}"
Completed updating config for mirror my-mirror.
$ bin/kafka-configs.sh --bootstrap-server :"${server4[cli]}" --entity-type mirrors --entity-name my-mirror --describe
Dynamic configs for mirror my-mirror are:
  bootstrap.servers=localhost:9092 sensitive=false synonyms={}
$ bin/kafka-mirrors.sh --bootstrap-server :"${server4[cli]}" --list
MIRROR                         TOPICS     SOURCE-BOOTSTRAP
my-mirror                      1          localhost:90929094
```

Signed-off-by: Federico Valeri <fedevaleri@gmail.com>